# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0'

gem 'bootsnap', require: false
gem 'puma'
gem 'rails', '~> 7.1'

# Grape ecosystem
gem 'grape', '~> 2.0'
gem 'grape-entity', '~> 1.0'
gem 'grape-swagger-entity', '~> 0.5'

# Use the local grape-swagger with OpenAPI 3.1 support
gem 'grape-swagger', path: '..'

# Development
group :development do
  gem 'listen'
end

# For JSON responses
gem 'multi_json'
gem 'oj'
